/* Refreshes the static snapshot in docs/ from the Next app.

   raheeqkanjo.com is GitHub Pages serving docs/, so editing app/ or
   globals.css changes nothing that visitors see until the snapshot is retaken.
   This does that: build, serve, fetch each public route, write it into docs/,
   and copy the hashed asset bundles across.

     node scripts/snapshot-docs.mjs

   Deliberately NOT snapshotted:
     /blog and /blog/<slug>  — those are generated by lib/siteGen.ts as
       crawlable static pages; overwriting them with the Next app's
       client-rendered list would drop the article text out of the HTML.
     /blog/p                 — a hand-written redirect for legacy links.

   Run it with the dev server stopped: building while `next dev` is running
   corrupts the dev server's .next and it starts 404-ing its own chunks. */

import { spawn } from "child_process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = path.join(ROOT, "docs");
const PORT = Number(process.env.SNAPSHOT_PORT) || 4573;

const ROUTES = [
  { url: "/", out: "index.html" },
  { url: "/linkedin", out: "linkedin/index.html" },
  { url: "/articles", out: "articles/index.html" },
  { url: "/scripts", out: "scripts/index.html" },
  { url: "/about", out: "about/index.html" },
  { url: "/contact", out: "contact/index.html" },
  { url: "/this-route-does-not-exist", out: "404.html" },
  { url: "/this-route-does-not-exist", out: "404/index.html" },
];

function run(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd: ROOT, stdio: "inherit", ...opts });
    child.on("exit", (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))
    );
  });
}

async function waitForServer(url, timeoutMs = 60_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const r = await fetch(url);
      if (r.ok || r.status === 404) return;
    } catch {
      /* not listening yet */
    }
    await new Promise((r) => setTimeout(r, 400));
  }
  throw new Error(`server did not come up at ${url}`);
}

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dst = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(src, dst);
    else fs.copyFileSync(src, dst);
  }
}

console.log("building…");
await run("npx", ["next", "build"]);

console.log(`serving on :${PORT}…`);
const server = spawn("npx", ["next", "start", "-p", String(PORT)], {
  cwd: ROOT,
  stdio: "ignore",
  env: { ...process.env, DATABASE_URL: "" },
});

try {
  await waitForServer(`http://127.0.0.1:${PORT}/`);

  for (const route of ROUTES) {
    const res = await fetch(`http://127.0.0.1:${PORT}${route.url}`);
    const html = await res.text();
    if (!html.includes("<nav id=\"nav\"")) {
      throw new Error(`${route.url} came back without the header nav — aborting`);
    }
    const dest = path.join(DOCS, route.out);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, html);
    console.log(`  ${route.url.padEnd(28)} -> docs/${route.out}  ${html.length}b`);
  }

  // Additive on purpose: pages this run did not rewrite still reference their
  // own older hashed bundles.
  copyDir(path.join(ROOT, ".next", "static"), path.join(DOCS, "_next", "static"));
  console.log("  copied .next/static -> docs/_next/static");

  /* The blog pages are generated by lib/siteGen.ts, not by this snapshot, so
     they keep whatever stylesheet hashes they were built with. Point them at
     the ones this build produced — ALL of them: the build splits the CSS into
     more than one chunk, and linking only the first leaves those pages without
     most of their styling. */
  const index = fs.readFileSync(path.join(DOCS, "index.html"), "utf8");
  const hrefs = [
    ...index.matchAll(/<link rel="stylesheet" href="(\/_next\/static\/css\/[^"]+\.css)"/g),
  ].map((m) => m[1]);

  if (!hrefs.length) throw new Error("no stylesheets found in the fresh snapshot");

  const links = hrefs.map((h) => `<link rel="stylesheet" href="${h}"/>`).join("\n");
  let touched = 0;
  const blogDir = path.join(DOCS, "blog");
  const walkBlog = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) walkBlog(p);
      else if (entry.name === "index.html") {
        const before = fs.readFileSync(p, "utf8");
        // collapse however many _next stylesheet links exist into the current set
        let seen = false;
        const after = before.replace(
          /<link rel="stylesheet" href="\/_next\/static\/css\/[^"]+\.css"\s*\/?>/g,
          () => (seen ? "" : ((seen = true), links))
        );
        if (after !== before) {
          fs.writeFileSync(p, after);
          touched++;
        }
      }
    }
  };
  if (fs.existsSync(blogDir)) walkBlog(blogDir);
  console.log(`  relinked ${touched} generated blog page(s) to ${hrefs.length} stylesheet(s)`);
} finally {
  server.kill();
}

console.log("\nsnapshot complete. docs/blog/* is generated separately by the publish step.");
